version: "3"

services:
  fluentd-collector:
    image: fluentd
    command:
      - "-c"
      - "/fluentd/etc/fluentd-collector.conf"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/log:/var/log
      - ${PWD}/configs:/fluentd/etc
    depends_on:
      - fluentd-aggregator

  fluentd-aggregator:
    image: grafana/fluent-plugin-loki:master
    command:
      - "fluentd"
      - "-p"
      - "/fluentd/plugins"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/configs/fluentd-aggregator.conf:/fluentd/etc/fluent.conf
    depends_on:
      - loki

  loki:
    image: grafana/loki:2.1.0
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/configs/loki-local-config.yaml:/etc/loki/config.yaml
    restart: always
    ports:
      - "3100:3100"
  
  grafana:
    image: grafana/grafana:latest
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - loki
    ports:
      - "3000:3000"
